public without sharing class oshIndividualChargentUpdateCCController {
    public oshIndividualChargentUpdateCCController() {
        //Cookie iframeDomainCookie = ApexPages.currentPage().getCookies();
        // system.debug('TEST from constructor');
        // system.debug(ApexPages.currentPage());
        // system.debug(String.valueOf(ApexPages.currentPage().getCookies()));
        // system.debug(ApexPages.currentPage().getCookies());
        // Cookie accessToken = new Cookie('counter','1',null,-1,true);
        // ApexPages.currentPage().setCookies(new Cookie[]{accessToken});
        // system.debug(String.valueOf(ApexPages.currentPage().getCookies()));
        //
        // if (iframeDomainCookie == null) {
        //     iframeDomainCookie = new Cookie('iframeDomain','www.example.com');
        //     // Set the new cookie for the page
        //     ApexPages.currentPage().setCookies(new Cookie[]{iframeDomainCookie});
        // }
    }

    // public void test(){
    //     system.debug('TEST from method test');
    //     system.debug(ApexPages.currentPage().getCookies());
    // }
}